#
# Copyright 2016 Red Hat, Inc.
#
# Red Hat licenses this file to you under the Apache License, version
# 2.0 (the "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#

---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    jkube.io/iconUrl: "https://cdn.rawgit.com/jkubeio.jkube-devops/master/jkube-docker-registry/src/main/jkube/icon.png"
  labels:
    provider: "jkube"
    app: "${project.artifactId}"
    version: "${project.version}"
    group: "io.jkube.devops.apps"
  name: "jkube-docker-registry"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      provider: "jkube"
      app: "${project.artifactId}"
      group: "io.jkube.devops.apps"
  template:
    metadata:
      labels:
        provider: "jkube"
        app: "${project.artifactId}"
        version: "${project.version}"
        group: "io.jkube.devops.apps"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "registry:2"
        imagePullPolicy: "IfNotPresent"
        name: "jkube-docker-registry"
        ports:
        - containerPort: 5000
          name: "http"
        volumeMounts:
        - mountPath: /var/lib/registry
          name: jkube-docker-registry-storage
          readOnly: false
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      volumes:
      - name: "jkube-docker-registry-storage"
        persistentVolumeClaim:
          claimName: jkube-docker-registry-storage
